spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: gestao-esportiva-api


  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    open-in-view: false
    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: false

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET:my_secret_key}
